name: check-wip-label
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - labeled
      - unlabeled
jobs:
  check-wip-label:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'WIP')
    steps:
      - name: fail
        run: |
          exit 1
